create table public.regions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  latitude double precision,
  longitude double precision,
  check (latitude is null or latitude between -90 and 90),
  check (longitude is null or longitude between -180 and 180)
);

create table public.companies (
  id bigint generated by default as identity primary key,
  name text not null
);

create table public.trips (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  departure_region_id bigint not null references public.regions(id),
  arrival_region_id bigint not null references public.regions(id),
  departure_time timestamptz not null,
  duration integer not null check (duration > 0),
  price integer not null check (price >= 0),
  total_seats integer not null check (total_seats > 0)
);

create table public.seats (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  seat_number integer not null,
  status text not null default 'libre' check (status in ('libre', 'reserve')),
  unique (trip_id, seat_number)
);

create table public.bookings (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id),
  seat_id bigint not null unique references public.seats(id),
  customer_name text not null,
  customer_phone text not null,
  payment_status text not null default 'en_attente',
  payment_reference text,
  created_at timestamptz not null default now()
);

alter table public.regions enable row level security;
alter table public.companies enable row level security;
alter table public.trips enable row level security;
alter table public.seats enable row level security;
alter table public.bookings enable row level security;

create policy "Public can read regions" on public.regions for select using (true);
create policy "Public can read companies" on public.companies for select using (true);
create policy "Public can read trips" on public.trips for select using (true);
create policy "Public can read seats" on public.seats for select using (true);
create policy "Public can create bookings" on public.bookings for insert with check (true);
create policy "Public can reserve seats" on public.seats for update using (true) with check (status = 'reserve');